language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
        - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
        - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get -y install qt510base qt510script qt510svg qt510imageformats qt510tools binutils zlib1g-dev xorg-dev gcc-7 g++-7
        - source /opt/qt510/bin/qt510-env.sh
      script:
        - source ./setup-qbs.sh
        - qbs --version
      after_success:
        - tar -zcvf qbs-1.12.2.tar.gz qbs-build
        - curl --upload-file qbs-1.12.2.tar.gz https://transfer.sh/qbs-1.12.2.tar.gz
