language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      script:
        - ls
        - tar -zcvf ThunderEngine.tar.gz README.md
        - ls
        - curl --upload-file ThunderEngine.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://ftp.thunderengine.ru/ThunderEngine.tar.gz
